/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:00bb2074-8da2-42a5-b5a3-6cf114f442cd",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_3aQ3sSyVl",
    "aws_user_pools_web_client_id": "51pov8ar1idghlp3a03aijaav9",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://6xb5qe64mraddf4epjqnfzzvm4.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-aoayvb6ngvacvbzsrzltlt56ua",
    "aws_user_files_s3_bucket": "uniquebucketname111823-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
