/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:00bb2074-8da2-42a5-b5a3-6cf114f442cd",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_3aQ3sSyVl",
    "aws_user_pools_web_client_id": "51pov8ar1idghlp3a03aijaav9",
    "oauth": {}
};


export default awsmobile;
